### PR TITLE
Added an installer

### PR DESCRIPTION
**Pull request by SimLeek**
It installs things

### CODE REVIEW

**Comment by okawo80085** [comment]
i'll test it later today and merge if it works fine

**Comment by okawo80085** [comment]
i finally got a minute on my windows machine, the exe installer that you provided doesnt register the driver with `vrpathreg`...

**Comment by okawo80085** [comment]
the culprit is the `driver_register_win.bat` script, i think it uses a relative path for the driver when running the register command...

**Comment by okawo80085** [comment]
since you already check if steamvr's vrpathreg is installed and where in your installer, you should execute the full `vrpathreg` command in it as well

**Comment by okawo80085** [comment]
everything else seems solid

**Comment by SimLeek** [comment]
Fixed and pushed. All the output is now in a details window too, so you can see the driver install / python install details.

**Comment by okawo80085** [comment]
Nice, I'll test it when I get to my windows machine again, thx

**Comment by okawo80085** [comment]
it works now

**Pull request merged**
